VERIFICATION_CODE_EXPIRATION = 600

VERIFICATION_LIMIT_PER_HOUR = 3
VERIFICATION_LIMIT_PER_DAY = 10
VERIFICATION_LOCKOUT_DAYS = 7

MIN_PASSWORD_LENGTH = 10

USERNAME_MIN_LENGTH = 3
USERNAME_MAX_LENGTH = 32

COPPA_MIN_AGE = 13

MAX_BIRTHDATE_RANGE_YEARS = 100

SESSION_TOKEN_LENGTH = 64

ALLOWED_EMAIL_DOMAINS = [
    "gmail.com",
    "outlook.com",
    "icloud.com",
    "yahoo.com",
    "mailfence.org"
]
